/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/scene.gltf -t -o src/pages/AboutPage/Donut.tsx 
Author: ¡Jacques (https://sketchfab.com/iJacques)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/donut-20-8d6cac74abfc4b408ec86c37661fa5a6
Title: Donut 2.0
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useState } from "react";
import { useSpring, animated, config } from "@react-spring/three";

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_8: THREE.Mesh;
  };
  materials: {
    donut: THREE.MeshStandardMaterial;
    icing: THREE.MeshPhysicalMaterial;
    sprinkles_bake: THREE.MeshStandardMaterial;
  };
  animations: any;
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export default function Donut(props: JSX.IntrinsicElements["group"]) {
  const [hovered, setHovered] = useState(false);

  const { nodes, materials } = useGLTF("/scene.gltf") as GLTFResult;
  materials.icing.transparent = true; // Enable transparency
  materials.icing.opacity = 0.8; // Set opacity to 80%
  materials.icing.metalness = 0.6;
  materials.icing.roughness = 0.5;
  const springs = useSpring({
    scale: hovered ? 6.5 : 6,
    config: config.gentle,
  });

  return (
    <animated.group {...props} dispose={null} castShadow {...springs}>
      <mesh
        castShadow
        geometry={nodes.Object_4.geometry}
        material={materials.donut}
        position={[0, 0.037, 0]}
      />
      <mesh
        onPointerOver={(e) => {
          e.stopPropagation(), setHovered(true);
        }}
        onPointerOut={(e) => {
          e.stopPropagation(), setHovered(false);
        }}
        castShadow
        geometry={nodes.Object_6.geometry}
        material={materials.icing}
        position={[0, 0.037, 0]}
      />
      <mesh
        castShadow
        geometry={nodes.Object_8.geometry}
        material={materials.sprinkles_bake}
        position={[0.076, 0.082, 0.009]}
        rotation={[1.448, 0.073, 3.007]}
        scale={0.141}
      />
    </animated.group>
  );
}

useGLTF.preload("/scene.gltf");
